enabled_layouts splits, stack

map ctrl+shift+j launch --location=hsplit
map ctrl+shift+k launch --location=vsplit

# Switch focus to the neighboring window in the indicated direction
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

# Resize windows
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter
# reset all windows in the tab to default sizes
map ctrl+home resize_window reset
# Maximize current pane (toggle)
map alt+m toggle_layout stack

#linux_display_server x11
# Opacity 0.9 is good if no blur
background_opacity 0.55

remember_window_size no

initial_window_width 120c
initial_window_height 35c

# Was 16 for x11
font_size 13.0
font_family JetBrainsMono Nerd Font


# BEGIN_KITTY_THEME
# Carbonfox
include current-theme.conf
# END_KITTY_THEME
