enabled_layouts splits, stack

# Create neighboring window
map ctrl+shift+j launch --location=hsplit
map ctrl+shift+k launch --location=vsplit

# Switch focus to another neighboring window
map alt+h neighboring_window left
map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down

# Resize a neighboring window
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter
# Reset all windows in the tab to default sizes
map ctrl+home resize_window reset
# Maximize current pane (toggle)
map alt+m toggle_layout stack

background_opacity 0.55
remember_window_size no
initial_window_width 120c
initial_window_height 35c

font_size 13.0
font_family JetBrainsMono Nerd Font


# BEGIN_KITTY_THEME
# Carbonfox
include current-theme.conf
# END_KITTY_THEME
