# Editor completions
"$schema" = 'https://starship.rs/config-schema.json'

format = "  $directory$git_branch$git_status$python$character"

[directory]
style = "bold #81F4E1"
truncation_length = 3
truncation_symbol = ''
truncate_to_repo = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''

[git_status]
staged = '+\($count\)'
modified = '!\($count\)'
ahead = '⇡{count}'
diverged = '⇕⇡{ahead_count}⇣{behind_count}'
behind = '⇣{count}'

[python]
style = 'bold #FFE74C'
format = '[\($virtualenv\)]($style) '

[character]
success_symbol = '[❯](bold #A19BFF) '
error_symbol = '[❯](bold red) '
