[config]
[templates.swaync]
input_path  = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook   = "swaync-client -rs"

[templates.waybar]
input_path  = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/css/colors.css"
post_hook   = 'pkill -SIGUSR2 waybar'

[templates.niri]
input_path  = "~/.config/matugen/templates/niri-colors.kdl"
output_path = "~/.config/niri/colors.kdl"

[templates.rofi]
input_path  = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.fastfetch]
input_path  = "~/.config/fastfetch/config.jsonc.template"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.swayosd]
input_path  = '~/.config/matugen/templates/swayosd-template.css'
output_path = '~/.config/swayosd/style.css'
post_hook   = "systemctl --user restart swayosd-server.service"
