general {
    lock_cmd = pidof hyprlock || hyprlock           # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session        # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on      # turn on display after sleep
    inhibit_sleep = 2                               # ignore idle + suspend
}

listener {
    timeout = 150                                    # 2.5 mins
    on-timeout = sh -c 'brightnessctl g > /tmp/idle_brightness && brightnessctl set 10%'
    on-resume = sh -c '[ -f /tmp/idle_brightness ] && brightnessctl s $(cat /tmp/idle_brightness)'
}

listener {
    timeout = 360                                    # 6 mins
    on-timeout = loginctl lock-session               # lock screen
}

listener {
    timeout = 360                                    # 6 mins
    on-timeout = niri msg action power-off-monitors  # turn off screen
    on-resume = niri msg action power-on-monitors
}
