general {
  hide_cursor = true
}

background {
  monitor =
  path = $HOME/.config/current_lockscreen
  blur_passes = 2
  blur_size = 4
}


label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(255, 255, 255, 0.8)

  font_size = 24
  font_family = JetBrainsMono Nerd Font

  position = 1187, 160
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M")"

  # Vertical time
  # text = cmd[update:1000] sh -c 'date +"%H"; date +"%M"'

  color = rgba(255, 255, 255, 1.0)
  font_size = 96
  font_family = JetBrainsMono Nerd Font

  position = 1176, 260
  halign = left
  valign = center
}

input-field {
  #size = 200, 50
  #position = 0, -340
  #halign = center
  #valign = center
  #placeholder_text = Try me, if you dare
  #fail_text = Incorrect. Launching B61-13 thermonuclear gravity bomb
  #font_family = JetBrainsMono Nerd Font

  #outer_color = rgba(255, 255, 255, 0.15)
  #inner_color = rgba(0, 0, 0, 0.4)
  #check_color = rgba(255,255,255,0.2)
  #fail_color = rgba(255,80,80,0.9)


  size = 350, 70
    position = 300, 100
    text_align = left
    outline_thickness = 0

    placeholder_text = 
    fail_text = 
    font_color = rgba(255, 255, 255, 0.1)
    font_family = JetBrainsMono Nerd Font

    outer_color = rgba(0, 0, 0, 0.0)
    inner_color = rgba(0, 0, 0, 0.0)
    check_color = rgba(0, 0, 0, 0.0)
    fail_color  = rgba(0, 0, 0, 0.0)
}
